# Generated by Django 6.1 on 2026-08-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=200)),
                ('school_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('main_competence', models.TextField()),
                ('specific_competence', models.TextField()),
                ('learning_activities', models.TextField()),
                ('teaching_materials', models.TextField()),
                ('assessment', models.TextField()),
                ('reflection', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
