# Generated by Django 6.1 on 2026-08-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='students_absent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='students_present',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='total_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='assessment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='learning_activities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='main_competence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='specific_competence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='teaching_materials',
            field=models.TextField(blank=True),
        ),
    ]
