# Generated by Django 6.1 on 2026-08-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplan', '0002_lessonplan_students_absent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Teacher', max_length=200)),
                ('school_name', models.CharField(blank=True, max_length=200)),
                ('subjects', models.CharField(blank=True, max_length=300)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('teacher_id', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
